"""
Queue-based traffic simulator.

The simulator converts generated vehicle and pedestrian demand into:
- queues
- waiting time
- throughput
- max queue length
- pedestrian delay metrics

It uses a simplified phase-based traffic-light model:
- NS green means north-south traffic moves and east-west waits
- EW green means east-west traffic moves and north-south waits
- pedestrian crossing is modelled as an intersection-level service phase

For Phase 3, we use fixed equal vehicle timing.
More advanced controllers will be added in later phases.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List

import numpy as np
import pandas as pd

from src.config import (
    DIRECTIONS,
    CYCLE_TIME,
    YELLOW_TIME,
    ALL_RED_TIME,
    BASE_SERVICE_RATE,
    SECONDS_PER_STEP,
    PEDESTRIAN_CROSSING_TIME,
    PEDESTRIAN_PHASE_TRIGGER,
    PEDESTRIAN_SERVICE_RATE,
)


@dataclass
class SimulationMetrics:
    """
    Final summary metrics for one simulation run.
    """

    avg_wait_time_seconds: float
    total_wait_time_seconds: float
    throughput: int
    total_arrivals: int
    final_queue_length: int
    max_queue_length: int
    avg_queue_length: float

    pedestrian_total_arrivals: int
    pedestrian_throughput: int
    pedestrian_final_queue: int
    pedestrian_max_queue: int
    pedestrian_avg_queue: float
    pedestrian_avg_wait_seconds: float
    pedestrian_total_wait_seconds: float


class QueueTrafficSimulator:
    """
    Queue-based simulator for a network of intersections.

    Parameters
    ----------
    num_intersections:
        Number of intersections in the road network.

    demand_df:
        Demand generated by src.data_generator.generate_traffic_demand.

    service_rate:
        Number of vehicles that can clear per second of green time
        under normal conditions.
    """

    def __init__(
        self,
        num_intersections: int,
        demand_df: pd.DataFrame,
        service_rate: float = BASE_SERVICE_RATE,
    ):
        self.num_intersections = num_intersections
        self.demand_df = demand_df.copy()
        self.service_rate = service_rate

        self.queues: Dict[int, Dict[str, int]] = {
            intersection_id: {direction: 0 for direction in DIRECTIONS}
            for intersection_id in range(num_intersections)
        }

        self.pedestrian_queues: Dict[int, int] = {
            intersection_id: 0
            for intersection_id in range(num_intersections)
        }

        self.total_arrivals = 0
        self.throughput = 0
        self.total_wait_time_seconds = 0.0

        self.max_queue_length = 0

        self.pedestrian_total_arrivals = 0
        self.pedestrian_throughput = 0
        self.pedestrian_total_wait_seconds = 0.0
        self.pedestrian_max_queue = 0

        self.history: List[Dict[str, float]] = []

    def run_fixed_equal(self) -> Dict[str, object]:
        """
        Run the simulation using equal green time for NS and EW.

        Returns
        -------
        dict
            Contains final metrics and time-series history.
        """
        time_steps = sorted(self.demand_df["time_step"].unique())

        for time_step in time_steps:
            step_demand = self.demand_df[
                self.demand_df["time_step"] == time_step
            ]

            self.step_fixed_equal(
                time_step=time_step,
                step_demand=step_demand,
            )

        metrics = self.get_metrics()

        return {
            "metrics": metrics,
            "history": pd.DataFrame(self.history),
        }

    def step_fixed_equal(
        self,
        time_step: int,
        step_demand: pd.DataFrame,
    ) -> None:
        """
        Run one simulation step using fixed equal signal timing.
        """
        self._add_arrivals(step_demand)

        green_times = self._fixed_equal_green_times()

        # Simple pedestrian phase:
        # If pedestrian queues are high, reserve crossing time.
        pedestrian_phase_active = self._should_activate_pedestrian_phase()

        if pedestrian_phase_active:
            self._serve_pedestrians()

        self._discharge_vehicles(
            step_demand=step_demand,
            green_times=green_times,
            pedestrian_phase_active=pedestrian_phase_active,
        )

        self._update_wait_times()

        self._record_history(
            time_step=time_step,
            pedestrian_phase_active=pedestrian_phase_active,
        )

    def _fixed_equal_green_times(self) -> Dict[str, float]:
        """
        Equal fixed timing baseline.

        We subtract yellow and all-red clearance time from the cycle,
        then split remaining green time equally between NS and EW.
        """
        available_green_time = (
            CYCLE_TIME
            - 2 * YELLOW_TIME
            - 2 * ALL_RED_TIME
        )

        green_per_direction = available_green_time / len(DIRECTIONS)

        return {
            direction: green_per_direction
            for direction in DIRECTIONS
        }

    def _add_arrivals(self, step_demand: pd.DataFrame) -> None:
        """
        Add vehicle and pedestrian arrivals to queues.
        """
        for _, row in step_demand.iterrows():
            intersection_id = int(row["intersection_id"])
            direction = row["direction"]
            vehicle_demand = int(row["vehicle_demand"])

            self.queues[intersection_id][direction] += vehicle_demand
            self.total_arrivals += vehicle_demand

        # Pedestrians are intersection-level, not direction-level.
        # Since demand_df has one row per direction, we avoid double-counting
        # by taking max pedestrian demand per intersection at this time step.
        pedestrian_by_intersection = (
            step_demand
            .groupby("intersection_id")["pedestrian_demand"]
            .max()
        )

        for intersection_id, pedestrian_demand in pedestrian_by_intersection.items():
            pedestrian_demand = int(pedestrian_demand)
            self.pedestrian_queues[int(intersection_id)] += pedestrian_demand
            self.pedestrian_total_arrivals += pedestrian_demand

    def _should_activate_pedestrian_phase(self) -> bool:
        """
        Decide whether to activate a pedestrian phase.

        This simple rule triggers crossing when at least one intersection
        has a pedestrian queue above a threshold.
        """
        return any(
            queue >= PEDESTRIAN_PHASE_TRIGGER
            for queue in self.pedestrian_queues.values()
        )

    def _serve_pedestrians(self) -> None:
        """
        Clear pedestrians during the pedestrian crossing phase.

        We treat pedestrian crossing as intersection-level service.
        """
        pedestrian_capacity = int(
            PEDESTRIAN_CROSSING_TIME * PEDESTRIAN_SERVICE_RATE
        )

        for intersection_id in range(self.num_intersections):
            current_queue = self.pedestrian_queues[intersection_id]
            pedestrians_crossed = min(current_queue, pedestrian_capacity)

            self.pedestrian_queues[intersection_id] -= pedestrians_crossed
            self.pedestrian_throughput += pedestrians_crossed

    def _discharge_vehicles(
        self,
        step_demand: pd.DataFrame,
        green_times: Dict[str, float],
        pedestrian_phase_active: bool,
    ) -> None:
        """
        Release vehicles from queues based on green time and capacity.

        Weather and accidents reduce capacity.
        Pedestrian phase reduces vehicle green time in this simplified model.
        """
        capacity_lookup = self._capacity_multipliers(step_demand)

        pedestrian_green_penalty = (
            PEDESTRIAN_CROSSING_TIME / len(DIRECTIONS)
            if pedestrian_phase_active
            else 0.0
        )

        for intersection_id in range(self.num_intersections):
            for direction in DIRECTIONS:
                queue_length = self.queues[intersection_id][direction]

                adjusted_green_time = max(
                    0.0,
                    green_times[direction] - pedestrian_green_penalty,
                )

                capacity_multiplier = capacity_lookup.get(
                    (intersection_id, direction),
                    1.0,
                )

                discharge_capacity = int(
                    adjusted_green_time
                    * self.service_rate
                    * capacity_multiplier
                )

                vehicles_released = min(queue_length, discharge_capacity)

                self.queues[intersection_id][direction] -= vehicles_released
                self.throughput += vehicles_released

    def _capacity_multipliers(
        self,
        step_demand: pd.DataFrame,
    ) -> Dict[tuple, float]:
        """
        Build capacity multiplier per intersection and direction.

        Weather reduces capacity.
        Accident further reduces capacity.
        """
        capacity_lookup = {}

        for _, row in step_demand.iterrows():
            intersection_id = int(row["intersection_id"])
            direction = row["direction"]

            weather_capacity = float(row["weather_capacity_multiplier"])

            accident_active = int(row["accident_active"])
            accident_capacity = 0.5 if accident_active == 1 else 1.0

            capacity_lookup[(intersection_id, direction)] = (
                weather_capacity * accident_capacity
            )

        return capacity_lookup

    def _update_wait_times(self) -> None:
        """
        Approximate waiting time.

        Any vehicle or pedestrian still in queue at the end of the minute
        is assumed to have waited for that minute.
        """
        total_vehicle_queue = self._total_vehicle_queue()
        total_pedestrian_queue = self._total_pedestrian_queue()

        self.total_wait_time_seconds += (
            total_vehicle_queue * SECONDS_PER_STEP
        )

        self.pedestrian_total_wait_seconds += (
            total_pedestrian_queue * SECONDS_PER_STEP
        )

    def _record_history(
        self,
        time_step: int,
        pedestrian_phase_active: bool,
    ) -> None:
        """
        Store time-series metrics for charts and Streamlit.
        """
        total_queue = self._total_vehicle_queue()
        pedestrian_queue = self._total_pedestrian_queue()

        ns_queue = self._direction_queue("NS")
        ew_queue = self._direction_queue("EW")

        self.max_queue_length = max(self.max_queue_length, total_queue)
        self.pedestrian_max_queue = max(
            self.pedestrian_max_queue,
            pedestrian_queue,
        )

        avg_queue_per_intersection = total_queue / self.num_intersections
        avg_pedestrian_queue_per_intersection = (
            pedestrian_queue / self.num_intersections
        )

        self.history.append(
            {
                "time_step": time_step,
                "total_queue": total_queue,
                "ns_queue": ns_queue,
                "ew_queue": ew_queue,
                "avg_queue_per_intersection": avg_queue_per_intersection,
                "throughput": self.throughput,
                "total_wait_time_seconds": self.total_wait_time_seconds,
                "pedestrian_queue": pedestrian_queue,
                "avg_pedestrian_queue_per_intersection": (
                    avg_pedestrian_queue_per_intersection
                ),
                "pedestrian_throughput": self.pedestrian_throughput,
                "pedestrian_wait_seconds": self.pedestrian_total_wait_seconds,
                "pedestrian_phase_active": int(pedestrian_phase_active),
            }
        )

    def _total_vehicle_queue(self) -> int:
        """
        Total queued vehicles across all intersections and directions.
        """
        return sum(
            self.queues[intersection_id][direction]
            for intersection_id in range(self.num_intersections)
            for direction in DIRECTIONS
        )

    def _total_pedestrian_queue(self) -> int:
        """
        Total queued pedestrians across all intersections.
        """
        return sum(self.pedestrian_queues.values())

    def _direction_queue(self, direction: str) -> int:
        """
        Total queued vehicles for one direction across all intersections.
        """
        return sum(
            self.queues[intersection_id][direction]
            for intersection_id in range(self.num_intersections)
        )

    def get_metrics(self) -> SimulationMetrics:
        """
        Return final simulation metrics.
        """
        avg_wait_time_seconds = (
            self.total_wait_time_seconds / self.total_arrivals
            if self.total_arrivals > 0
            else 0.0
        )

        avg_queue_length = (
            np.mean([row["total_queue"] for row in self.history])
            if self.history
            else 0.0
        )

        pedestrian_avg_queue = (
            np.mean([row["pedestrian_queue"] for row in self.history])
            if self.history
            else 0.0
        )

        pedestrian_avg_wait_seconds = (
            self.pedestrian_total_wait_seconds / self.pedestrian_total_arrivals
            if self.pedestrian_total_arrivals > 0
            else 0.0
        )

        return SimulationMetrics(
            avg_wait_time_seconds=avg_wait_time_seconds,
            total_wait_time_seconds=self.total_wait_time_seconds,
            throughput=self.throughput,
            total_arrivals=self.total_arrivals,
            final_queue_length=self._total_vehicle_queue(),
            max_queue_length=self.max_queue_length,
            avg_queue_length=float(avg_queue_length),
            pedestrian_total_arrivals=self.pedestrian_total_arrivals,
            pedestrian_throughput=self.pedestrian_throughput,
            pedestrian_final_queue=self._total_pedestrian_queue(),
            pedestrian_max_queue=self.pedestrian_max_queue,
            pedestrian_avg_queue=float(pedestrian_avg_queue),
            pedestrian_avg_wait_seconds=pedestrian_avg_wait_seconds,
            pedestrian_total_wait_seconds=self.pedestrian_total_wait_seconds,
        )


def run_fixed_equal_simulation(
    num_intersections: int,
    demand_df: pd.DataFrame,
) -> Dict[str, object]:
    """
    Convenience function for Phase 3 testing.
    """
    simulator = QueueTrafficSimulator(
        num_intersections=num_intersections,
        demand_df=demand_df,
    )

    return simulator.run_fixed_equal()