"""
Queue-based traffic simulator.

The simulator converts generated vehicle and pedestrian demand into:
- queues
- waiting time
- throughput
- max queue length
- pedestrian delay metrics

It uses a simplified phase-based traffic-light model:
- NS green means north-south traffic moves and east-west waits
- EW green means east-west traffic moves and north-south waits
- pedestrian crossing is modelled as an intersection-level service phase

For Phase 3, we use fixed equal vehicle timing.
More advanced controllers will be added in later phases.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List
import copy

import numpy as np
import pandas as pd
from src.controllers import (
    BaseTrafficController,
    FixedEqualController,
    FixedCalibratedController,
    AdaptivePressureController,
    EnhancedAdaptiveController,
    GATimingPlanController,
)
from src.event_log import EventLogger
from src.emergency import (
    find_emergency_route,
    infer_movement_direction,
)

from src.config import (
    DIRECTIONS,
    CYCLE_TIME,
    YELLOW_TIME,
    ALL_RED_TIME,
    BASE_SERVICE_RATE,
    SECONDS_PER_STEP,
    PEDESTRIAN_MIN_GAP_STEPS,
    PEDESTRIAN_CROSSING_TIME,
    PEDESTRIAN_PHASE_TRIGGER,
    PEDESTRIAN_SERVICE_RATE,
    ENABLE_ACTUATED_REALLOCATION,
    MAX_REALLOCATED_GREEN_SECONDS,
    EMERGENCY_SCENARIOS,
    EMERGENCY_DISPATCH_STEP,
    EMERGENCY_ORIGIN_INTERSECTION,
    EMERGENCY_DESTINATION_INTERSECTION,
    EMERGENCY_BASE_TRAVEL_TIME,
    EMERGENCY_QUEUE_DELAY_WEIGHT,
    EMERGENCY_ACCIDENT_PENALTY,
    EMERGENCY_ROUTE_ADVANCE_STEPS,
    EMERGENCY_PRIORITY_GREEN,
    EMERGENCY_CONFLICT_GREEN,
    EMERGENCY_PREEMPTION_DELAY_SECONDS,
    EMERGENCY_NO_PRIORITY_BASE_DELAY_SECONDS,
    EMERGENCY_NO_PRIORITY_QUEUE_DELAY_WEIGHT,
    ENABLE_PEDESTRIAN_FAIRNESS,
    PEDESTRIAN_FORCE_CROSSING_QUEUE,
    PEDESTRIAN_MAX_WAIT_SECONDS,
    PEDESTRIAN_TARGET_AVG_WAIT_SECONDS,
)


@dataclass
class SimulationMetrics:
    """
    Final summary metrics for one simulation run.
    """

    avg_wait_time_seconds: float
    total_wait_time_seconds: float
    throughput: int
    total_arrivals: int
    final_queue_length: int
    max_queue_length: int
    avg_queue_length: float

    pedestrian_total_arrivals: int
    pedestrian_throughput: int
    pedestrian_final_queue: int
    pedestrian_max_queue: int
    pedestrian_avg_queue: float
    pedestrian_avg_wait_seconds: float
    pedestrian_total_wait_seconds: float

    emergency_dispatched: int = 0
    emergency_completed: int = 0
    emergency_route_length: int = 0
    emergency_delay_seconds: float = 0.0
    emergency_preemptions: int = 0
    emergency_completion_step: int = -1

    pedestrian_target_wait_seconds: float = 0.0
    pedestrian_target_met: int = 0
    pedestrian_max_estimated_wait_seconds: float = 0.0
    pedestrian_fairness_gap_seconds: float = 0.0


class QueueTrafficSimulator:
    """
    Queue-based simulator for a network of intersections.

    Parameters
    ----------
    num_intersections:
        Number of intersections in the road network.

    demand_df:
        Demand generated by src.data_generator.generate_traffic_demand.

    service_rate:
        Number of vehicles that can clear per second of green time
        under normal conditions.
    """

    def __init__(
        self,
        num_intersections: int,
        demand_df: pd.DataFrame,
        service_rate: float = BASE_SERVICE_RATE,
        scenario: str = "normal",
        enable_emergency_priority: bool = True,
    ):
        self.num_intersections = num_intersections
        self.demand_df = demand_df.copy()
        self.service_rate = service_rate

        self.queues: Dict[int, Dict[str, int]] = {
            intersection_id: {direction: 0 for direction in DIRECTIONS}
            for intersection_id in range(num_intersections)
        }

        self.pedestrian_queues: Dict[int, int] = {
            intersection_id: 0
            for intersection_id in range(num_intersections)
        }

        self.pedestrian_queue_age_steps: Dict[int, int] = {
            intersection_id: 0
            for intersection_id in range(num_intersections)
        }

        self.last_pedestrian_service_step: Dict[int, int] = {
            intersection_id: -10_000
            for intersection_id in range(num_intersections)
        }

        self.total_arrivals = 0
        self.throughput = 0
        self.total_wait_time_seconds = 0.0

        self.max_queue_length = 0

        self.pedestrian_total_arrivals = 0
        self.pedestrian_throughput = 0
        self.pedestrian_total_wait_seconds = 0.0
        self.pedestrian_max_queue = 0
        self.pedestrian_max_estimated_wait_seconds_observed = 0.0

        self.history: List[Dict[str, float]] = []

        self.scenario = scenario
        self.enable_emergency_priority = enable_emergency_priority

        self.event_logger = EventLogger()

        # Emergency state
        self.emergency_route = None
        self.emergency_active = False
        self.emergency_completed = False
        self.emergency_dispatch_step = None
        self.emergency_completion_step = -1
        self.emergency_delay_seconds = 0.0
        self.emergency_preemptions = 0
        self.emergency_current_intersection = None

    def run(
            self,
            controller: BaseTrafficController,
    ) -> Dict[str, object]:
        """
        Run the simulation using a supplied traffic-light controller.

        The simulator handles queues, arrivals, service, waiting time,
        and metrics. The controller only decides green-time allocation.
        """
        time_steps = sorted(self.demand_df["time_step"].unique())

        for time_step in time_steps:
            step_demand = self.demand_df[
                self.demand_df["time_step"] == time_step
                ]

            self.step(
                time_step=time_step,
                step_demand=step_demand,
                controller=controller,
            )

        metrics = self.get_metrics()

        return {
            "metrics": metrics,
            "history": pd.DataFrame(self.history),
            "event_log": self.get_event_log(),
        }

    def step(
            self,
            time_step: int,
            step_demand: pd.DataFrame,
            controller: BaseTrafficController,
    ) -> None:
        """
        Run one simulation step using the supplied controller.
        """
        self._add_arrivals(step_demand)

        simulator_state = self.get_state()

        decision = controller.get_green_times(
            time_step=time_step,
            num_intersections=self.num_intersections,
            step_demand=step_demand,
            simulator_state=simulator_state,
        )

        self._maybe_dispatch_emergency(
            time_step=time_step,
            step_demand=step_demand,
        )

        green_times = copy.deepcopy(decision.green_times)

        emergency_info = self._apply_emergency_preemption(
            time_step=time_step,
            green_times_by_intersection=green_times,
        )

        pedestrian_phase_by_intersection = self._pedestrian_phase_by_intersection(
            time_step=time_step,
        )

        if any(pedestrian_phase_by_intersection.values()):
            self._serve_pedestrians(
                time_step=time_step,
                pedestrian_phase_by_intersection=pedestrian_phase_by_intersection,
            )

        self._discharge_vehicles(
            step_demand=step_demand,
            green_times_by_intersection=green_times,
            pedestrian_phase_by_intersection=pedestrian_phase_by_intersection,
            allow_actuated_reallocation=decision.allow_actuated_reallocation,
        )

        self._update_wait_times()

        self._record_history(
            time_step=time_step,
            pedestrian_phase_by_intersection=pedestrian_phase_by_intersection,
            controller_name=decision.controller_name,
            green_times_by_intersection=green_times,
            allow_actuated_reallocation=decision.allow_actuated_reallocation,
            emergency_info=emergency_info,
        )

    def get_state(self) -> Dict:
        """
        Return current simulator state for controllers.

        Later adaptive controllers will use this to inspect queues.
        """
        return {
            "queues": self.queues,
            "pedestrian_queues": self.pedestrian_queues,
            "total_vehicle_queue": self._total_vehicle_queue(),
            "total_pedestrian_queue": self._total_pedestrian_queue(),
            "throughput": self.throughput,
            "total_arrivals": self.total_arrivals,
        }

    def _fixed_equal_green_times(self) -> Dict[str, float]:
        """
        Equal fixed timing baseline.

        We subtract yellow and all-red clearance time from the cycle,
        then split remaining green time equally between NS and EW.
        """
        available_green_time = (
            CYCLE_TIME
            - 2 * YELLOW_TIME
            - 2 * ALL_RED_TIME
        )

        green_per_direction = available_green_time / len(DIRECTIONS)

        return {
            direction: green_per_direction
            for direction in DIRECTIONS
        }

    def _add_arrivals(self, step_demand: pd.DataFrame) -> None:
        """
        Add vehicle and pedestrian arrivals to queues.
        """
        for _, row in step_demand.iterrows():
            intersection_id = int(row["intersection_id"])
            direction = row["direction"]
            vehicle_demand = int(row["vehicle_demand"])

            self.queues[intersection_id][direction] += vehicle_demand
            self.total_arrivals += vehicle_demand
            for intersection_id in range(self.num_intersections):
                if self.pedestrian_queues[intersection_id] > 0:
                    self.pedestrian_queue_age_steps[intersection_id] += 1
                else:
                    self.pedestrian_queue_age_steps[intersection_id] = 0

        # Pedestrians are intersection-level, not direction-level.
        # Since demand_df has one row per direction, we avoid double-counting
        # by taking max pedestrian demand per intersection at this time step.
        pedestrian_by_intersection = (
            step_demand
            .groupby("intersection_id")["pedestrian_demand"]
            .max()
        )

        for intersection_id, pedestrian_demand in pedestrian_by_intersection.items():
            pedestrian_demand = int(pedestrian_demand)
            self.pedestrian_queues[int(intersection_id)] += pedestrian_demand
            self.pedestrian_total_arrivals += pedestrian_demand

    def _pedestrian_phase_by_intersection(
            self,
            time_step: int,
    ) -> Dict[int, bool]:
        """
        Decide pedestrian phase activation per intersection.

        Balanced policy:
        - Trigger when pedestrian queue is meaningfully large.
        - Force crossing if queue is very large.
        - Force crossing if there has been no pedestrian service for too long.
        - All triggers respect a minimum gap between crossings.

        This avoids pedestrian starvation without allowing pedestrian phases
        to dominate vehicle flow.
        """
        phase_active = {}

        for intersection_id, queue in self.pedestrian_queues.items():
            last_service_step = self.last_pedestrian_service_step[intersection_id]

            steps_since_service = time_step - last_service_step
            cooldown_passed = steps_since_service >= PEDESTRIAN_MIN_GAP_STEPS

            estimated_wait_since_service_seconds = (
                steps_since_service * SECONDS_PER_STEP
                if queue > 0
                else 0
            )

            normal_trigger = (
                    queue >= PEDESTRIAN_PHASE_TRIGGER
                    and cooldown_passed
            )

            force_by_queue = (
                    ENABLE_PEDESTRIAN_FAIRNESS
                    and queue >= PEDESTRIAN_FORCE_CROSSING_QUEUE
                    and cooldown_passed
            )

            force_by_wait = (
                    ENABLE_PEDESTRIAN_FAIRNESS
                    and estimated_wait_since_service_seconds >= PEDESTRIAN_MAX_WAIT_SECONDS
                    and cooldown_passed
            )

            phase_active[intersection_id] = (
                    normal_trigger
                    or force_by_queue
                    or force_by_wait
            )

            if phase_active[intersection_id]:
                trigger_reason = "normal queue threshold"

                if force_by_queue:
                    trigger_reason = "large pedestrian queue"

                if force_by_wait:
                    trigger_reason = "max time since service exceeded"

                self.event_logger.log(
                    time_step=time_step,
                    event_type="pedestrian_phase",
                    message=(
                        f"Pedestrian phase activated at intersection "
                        f"{intersection_id}. Reason: {trigger_reason}. "
                        f"Queue: {queue}, time since service: "
                        f"{estimated_wait_since_service_seconds:.0f}s."
                    ),
                    severity="info",
                    dedupe_key=f"pedestrian_phase_{time_step}_{intersection_id}",
                )

        return phase_active

    def _serve_pedestrians(
            self,
            time_step: int,
            pedestrian_phase_by_intersection: Dict[int, bool],
    ) -> None:
        """
        Clear pedestrians only at intersections where the pedestrian phase is active.
        """
        pedestrian_capacity = int(
            PEDESTRIAN_CROSSING_TIME * PEDESTRIAN_SERVICE_RATE
        )

        for intersection_id, phase_active in pedestrian_phase_by_intersection.items():
            if not phase_active:
                continue

            current_queue = self.pedestrian_queues[intersection_id]
            pedestrians_crossed = min(current_queue, pedestrian_capacity)

            self.pedestrian_queues[intersection_id] -= pedestrians_crossed
            self.pedestrian_throughput += pedestrians_crossed
            self.last_pedestrian_service_step[intersection_id] = time_step
            self.pedestrian_queue_age_steps[intersection_id] = 0

            if self.pedestrian_queues[intersection_id] == 0:
                self.pedestrian_queue_age_steps[intersection_id] = 0
            else:
                # Some pedestrians remain, so the oldest wait continues.
                self.pedestrian_queue_age_steps[intersection_id] = max(
                    1,
                    self.pedestrian_queue_age_steps[intersection_id],
                )

    def _discharge_vehicles(
            self,
            step_demand: pd.DataFrame,
            green_times_by_intersection: Dict[int, Dict[str, float]],
            pedestrian_phase_by_intersection: Dict[int, bool],
            allow_actuated_reallocation: bool,
    ) -> None:
        """
        Release vehicles from queues based on green time and capacity.

        Weather and accidents reduce capacity.
        Pedestrian phase reduces vehicle green time only at active intersections.

        Actuated reallocation:
            If one direction does not use all of its green capacity, some unused
            green time can be transferred to the opposite direction.
        """
        capacity_lookup = self._capacity_multipliers(step_demand)

        for intersection_id in range(self.num_intersections):
            intersection_green_times = green_times_by_intersection[intersection_id]

            pedestrian_green_penalty = (
                PEDESTRIAN_CROSSING_TIME / len(DIRECTIONS)
                if pedestrian_phase_by_intersection.get(intersection_id, False)
                else 0.0
            )

            adjusted_green_times = {}

            for direction in DIRECTIONS:
                adjusted_green_times[direction] = max(
                    0.0,
                    intersection_green_times[direction] - pedestrian_green_penalty,
                )

            if ENABLE_ACTUATED_REALLOCATION and allow_actuated_reallocation:
                adjusted_green_times = self._apply_actuated_reallocation(
                    intersection_id=intersection_id,
                    adjusted_green_times=adjusted_green_times,
                    capacity_lookup=capacity_lookup,
                )

            for direction in DIRECTIONS:
                queue_length = self.queues[intersection_id][direction]

                capacity_multiplier = capacity_lookup.get(
                    (intersection_id, direction),
                    1.0,
                )

                discharge_capacity = int(
                    adjusted_green_times[direction]
                    * self.service_rate
                    * capacity_multiplier
                )

                vehicles_released = min(queue_length, discharge_capacity)

                self.queues[intersection_id][direction] -= vehicles_released
                self.throughput += vehicles_released

    def _apply_actuated_reallocation(
            self,
            intersection_id: int,
            adjusted_green_times: Dict[str, float],
            capacity_lookup: Dict[tuple, float],
    ) -> Dict[str, float]:
        """
        Reallocate unused green time from a low-demand direction to a
        high-demand direction.

        This mimics actuated traffic signals that terminate a phase early
        when demand is low.
        """
        updated_green_times = adjusted_green_times.copy()

        unused_green_by_direction = {}

        for direction in DIRECTIONS:
            queue_length = self.queues[intersection_id][direction]

            capacity_multiplier = capacity_lookup.get(
                (intersection_id, direction),
                1.0,
            )

            effective_service_rate = max(
                self.service_rate * capacity_multiplier,
                1e-6,
            )

            required_green_to_clear_queue = queue_length / effective_service_rate

            unused_green = max(
                0.0,
                adjusted_green_times[direction] - required_green_to_clear_queue,
            )

            unused_green_by_direction[direction] = unused_green

        ns_unused = unused_green_by_direction["NS"]
        ew_unused = unused_green_by_direction["EW"]

        ns_queue = self.queues[intersection_id]["NS"]
        ew_queue = self.queues[intersection_id]["EW"]

        if ns_unused > 0 and ew_queue > ns_queue:
            transfer = min(ns_unused, MAX_REALLOCATED_GREEN_SECONDS)
            updated_green_times["NS"] -= transfer
            updated_green_times["EW"] += transfer

        elif ew_unused > 0 and ns_queue > ew_queue:
            transfer = min(ew_unused, MAX_REALLOCATED_GREEN_SECONDS)
            updated_green_times["EW"] -= transfer
            updated_green_times["NS"] += transfer

        return updated_green_times

    def _capacity_multipliers(
        self,
        step_demand: pd.DataFrame,
    ) -> Dict[tuple, float]:
        """
        Build capacity multiplier per intersection and direction.

        Weather reduces capacity.
        Accident further reduces capacity.
        """
        capacity_lookup = {}

        for _, row in step_demand.iterrows():
            intersection_id = int(row["intersection_id"])
            direction = row["direction"]

            weather_capacity = float(row["weather_capacity_multiplier"])

            accident_active = int(row["accident_active"])
            accident_capacity = 0.5 if accident_active == 1 else 1.0

            capacity_lookup[(intersection_id, direction)] = (
                weather_capacity * accident_capacity
            )

        return capacity_lookup

    def _update_wait_times(self) -> None:
        """
        Approximate waiting time.

        Any vehicle or pedestrian still in queue at the end of the minute
        is assumed to have waited for that minute.
        """
        total_vehicle_queue = self._total_vehicle_queue()
        total_pedestrian_queue = self._total_pedestrian_queue()

        self.total_wait_time_seconds += (
            total_vehicle_queue * SECONDS_PER_STEP
        )

        self.pedestrian_total_wait_seconds += (
            total_pedestrian_queue * SECONDS_PER_STEP
        )

    def _record_history(
            self,
            time_step: int,
            pedestrian_phase_by_intersection: Dict[int, bool],
            controller_name: str,
            green_times_by_intersection: Dict[int, Dict[str, float]],
            allow_actuated_reallocation: bool,
            emergency_info: Dict[str, object] | None = None,
    ) -> None:
        """
        Store time-series metrics for charts and Streamlit.
        """
        total_queue = self._total_vehicle_queue()
        pedestrian_queue = self._total_pedestrian_queue()

        ns_queue = self._direction_queue("NS")
        ew_queue = self._direction_queue("EW")

        self.max_queue_length = max(self.max_queue_length, total_queue)
        self.pedestrian_max_queue = max(
            self.pedestrian_max_queue,
            pedestrian_queue,
        )

        pedestrian_active_intersections = sum(
            int(active)
            for active in pedestrian_phase_by_intersection.values()
        )

        avg_queue_per_intersection = total_queue / self.num_intersections
        avg_pedestrian_queue_per_intersection = (
            pedestrian_queue / self.num_intersections
        )
        avg_ns_green = np.mean(
            [
                green_times_by_intersection[i]["NS"]
                for i in range(self.num_intersections)
            ]
        )

        avg_ew_green = np.mean(
            [
                green_times_by_intersection[i]["EW"]
                for i in range(self.num_intersections)
            ]
        )
        if emergency_info is None:
            emergency_info = {
                "emergency_active": 0,
                "emergency_preemption_active": 0,
                       "emergency_current_intersection": -1,
            }

        pedestrian_max_estimated_wait_seconds = 0.0

        for intersection_id, queue in self.pedestrian_queues.items():
            if queue <= 0:
                continue

            last_service_step = self.last_pedestrian_service_step[intersection_id]
            steps_since_service = time_step - last_service_step

            pedestrian_max_estimated_wait_seconds = max(
                pedestrian_max_estimated_wait_seconds,
                steps_since_service * SECONDS_PER_STEP,
            )

        self.pedestrian_max_estimated_wait_seconds_observed = max(
            self.pedestrian_max_estimated_wait_seconds_observed,
            pedestrian_max_estimated_wait_seconds,
        )

        self.history.append(
            {
                "time_step": time_step,
                "controller": controller_name,
                "total_queue": total_queue,
                "ns_queue": ns_queue,
                "ew_queue": ew_queue,
                "avg_queue_per_intersection": avg_queue_per_intersection,
                "throughput": self.throughput,
                "total_wait_time_seconds": self.total_wait_time_seconds,
                "pedestrian_queue": pedestrian_queue,
                "avg_pedestrian_queue_per_intersection": (
                    avg_pedestrian_queue_per_intersection
                ),
                "pedestrian_throughput": self.pedestrian_throughput,
                "pedestrian_wait_seconds": self.pedestrian_total_wait_seconds,
                "pedestrian_phase_active": int(pedestrian_active_intersections > 0),
                "pedestrian_active_intersections": pedestrian_active_intersections,
                "avg_ns_green": avg_ns_green,
                "allow_actuated_reallocation": int(allow_actuated_reallocation),
                "avg_ew_green": avg_ew_green,
                "emergency_active": emergency_info["emergency_active"],
                "emergency_preemption_active": emergency_info["emergency_preemption_active"],
                "emergency_current_intersection": emergency_info["emergency_current_intersection"],
                "emergency_delay_seconds": self.emergency_delay_seconds,
                "emergency_preemptions": self.emergency_preemptions,
                "pedestrian_max_estimated_wait_seconds": (
                    pedestrian_max_estimated_wait_seconds
                ),
                "pedestrian_target_wait_seconds": PEDESTRIAN_TARGET_AVG_WAIT_SECONDS,
            }
        )

    def _total_vehicle_queue(self) -> int:
        """
        Total queued vehicles across all intersections and directions.
        """
        return sum(
            self.queues[intersection_id][direction]
            for intersection_id in range(self.num_intersections)
            for direction in DIRECTIONS
        )

    def _total_pedestrian_queue(self) -> int:
        """
        Total queued pedestrians across all intersections.
        """
        return sum(self.pedestrian_queues.values())

    def _direction_queue(self, direction: str) -> int:
        """
        Total queued vehicles for one direction across all intersections.
        """
        return sum(
            self.queues[intersection_id][direction]
            for intersection_id in range(self.num_intersections)
        )

    def get_metrics(self) -> SimulationMetrics:
        """
        Return final simulation metrics.
        """
        avg_wait_time_seconds = (
            self.total_wait_time_seconds / self.total_arrivals
            if self.total_arrivals > 0
            else 0.0
        )

        avg_queue_length = (
            np.mean([row["total_queue"] for row in self.history])
            if self.history
            else 0.0
        )

        pedestrian_avg_queue = (
            np.mean([row["pedestrian_queue"] for row in self.history])
            if self.history
            else 0.0
        )

        pedestrian_avg_wait_seconds = (
            self.pedestrian_total_wait_seconds / self.pedestrian_total_arrivals
            if self.pedestrian_total_arrivals > 0
            else 0.0
        )
        pedestrian_max_estimated_wait_seconds = (
            self.pedestrian_max_estimated_wait_seconds_observed
        )

        pedestrian_fairness_gap_seconds = max(
            0.0,
            pedestrian_avg_wait_seconds - PEDESTRIAN_TARGET_AVG_WAIT_SECONDS,
        )

        pedestrian_target_met = int(
            pedestrian_avg_wait_seconds <= PEDESTRIAN_TARGET_AVG_WAIT_SECONDS
        )

        return SimulationMetrics(
            avg_wait_time_seconds=avg_wait_time_seconds,
            total_wait_time_seconds=self.total_wait_time_seconds,
            throughput=self.throughput,
            total_arrivals=self.total_arrivals,
            final_queue_length=self._total_vehicle_queue(),
            max_queue_length=self.max_queue_length,
            avg_queue_length=float(avg_queue_length),
            pedestrian_total_arrivals=self.pedestrian_total_arrivals,
            pedestrian_throughput=self.pedestrian_throughput,
            pedestrian_final_queue=self._total_pedestrian_queue(),
            pedestrian_max_queue=self.pedestrian_max_queue,
            pedestrian_avg_queue=float(pedestrian_avg_queue),
            pedestrian_avg_wait_seconds=pedestrian_avg_wait_seconds,
            pedestrian_total_wait_seconds=self.pedestrian_total_wait_seconds,
            emergency_dispatched=int(self.emergency_route is not None),
            emergency_completed=int(self.emergency_completed),
            emergency_route_length=(
                len(self.emergency_route)
                if self.emergency_route is not None
                else 0
            ),
            emergency_delay_seconds=self.emergency_delay_seconds,
            emergency_preemptions=self.emergency_preemptions,
            emergency_completion_step=self.emergency_completion_step,
            pedestrian_target_wait_seconds=PEDESTRIAN_TARGET_AVG_WAIT_SECONDS,
            pedestrian_target_met=pedestrian_target_met,
            pedestrian_max_estimated_wait_seconds=pedestrian_max_estimated_wait_seconds,
            pedestrian_fairness_gap_seconds=pedestrian_fairness_gap_seconds,
        )

    def get_event_log(self) -> pd.DataFrame:
        return self.event_logger.to_dataframe()

    def _scenario_supports_emergency(self) -> bool:
        return self.scenario in EMERGENCY_SCENARIOS

    def _accident_context_from_step(
            self,
            step_demand: pd.DataFrame,
    ) -> Dict[str, object]:
        """
        Extract accident context from current demand frame.
        """
        accident_active = False
        accident_intersection = None

        if "accident_active" in step_demand.columns:
            accident_active = int(step_demand["accident_active"].max()) == 1

            if accident_active:
                affected = step_demand[step_demand["accident_active"] == 1]
                if not affected.empty:
                    accident_intersection = int(
                        affected["intersection_id"].iloc[0]
                    )

        return {
            "accident_active": accident_active,
            "accident_intersection": accident_intersection,
        }

    def _maybe_dispatch_emergency(
            self,
            time_step: int,
            step_demand: pd.DataFrame,
    ) -> None:
        """
        Dispatch emergency vehicle once during emergency scenario.
        """
        if not self._scenario_supports_emergency():
            return

        if self.emergency_route is not None:
            return

        if time_step != EMERGENCY_DISPATCH_STEP:
            return

        destination = (
            self.num_intersections - 1
            if EMERGENCY_DESTINATION_INTERSECTION is None
            else EMERGENCY_DESTINATION_INTERSECTION
        )

        simulator_state = self.get_state()
        simulator_state.update(
            self._accident_context_from_step(step_demand)
        )

        route_result = find_emergency_route(
            num_intersections=self.num_intersections,
            origin=EMERGENCY_ORIGIN_INTERSECTION,
            destination=destination,
            simulator_state=simulator_state,
            base_travel_time=EMERGENCY_BASE_TRAVEL_TIME,
            queue_weight=EMERGENCY_QUEUE_DELAY_WEIGHT,
            accident_penalty=EMERGENCY_ACCIDENT_PENALTY,
        )

        self.emergency_route = route_result.route
        self.emergency_active = True
        self.emergency_dispatch_step = time_step
        self.emergency_current_intersection = route_result.route[0]

        self.event_logger.log(
            time_step=time_step,
            event_type="emergency_dispatch",
            message=(
                f"Emergency vehicle dispatched from intersection "
                f"{route_result.origin} to {route_result.destination}. "
                f"Route selected: {route_result.route}."
            ),
            severity="warning",
            dedupe_key="emergency_dispatch",
        )

    def _current_emergency_segment(
            self,
            time_step: int,
    ) -> tuple[int, int] | None:
        """
        Return current route segment as (source, target).

        Emergency vehicle advances one route segment every
        EMERGENCY_ROUTE_ADVANCE_STEPS simulation steps.
        """
        if not self.emergency_active:
            return None

        if self.emergency_route is None:
            return None

        if self.emergency_completed:
            return None

        route_progress = (
                (time_step - self.emergency_dispatch_step)
                // EMERGENCY_ROUTE_ADVANCE_STEPS
        )

        if route_progress >= len(self.emergency_route) - 1:
            self.emergency_completed = True
            self.emergency_active = False
            self.emergency_completion_step = time_step

            self.event_logger.log(
                time_step=time_step,
                event_type="emergency_complete",
                message=(
                    "Emergency vehicle reached destination. "
                    f"Total emergency delay: "
                    f"{self.emergency_delay_seconds:.1f} seconds."
                ),
                severity="success",
                dedupe_key="emergency_complete",
            )

            return None

        source = self.emergency_route[route_progress]
        target = self.emergency_route[route_progress + 1]

        self.emergency_current_intersection = source

        return source, target

    def _apply_emergency_preemption(
            self,
            time_step: int,
            green_times_by_intersection: Dict[int, Dict[str, float]],
    ) -> Dict[str, object]:
        """
        Override green times for the intersection currently used by the
        emergency vehicle.

        Returns event info for history logging.
        """
        info = {
            "emergency_active": int(self.emergency_active),
            "emergency_preemption_active": 0,
            "emergency_current_intersection": -1,
        }

        segment = self._current_emergency_segment(time_step)

        if segment is None:
            return info

        source, target = segment
        direction = infer_movement_direction(
            source=source,
            target=target,
            num_intersections=self.num_intersections,
        )

        info["emergency_current_intersection"] = source

        if self.enable_emergency_priority:
            if direction == "NS":
                green_times_by_intersection[source] = {
                    "NS": EMERGENCY_PRIORITY_GREEN,
                    "EW": EMERGENCY_CONFLICT_GREEN,
                }
            else:
                green_times_by_intersection[source] = {
                    "NS": EMERGENCY_CONFLICT_GREEN,
                    "EW": EMERGENCY_PRIORITY_GREEN,
                }

            self.emergency_preemptions += 1
            self.emergency_delay_seconds += EMERGENCY_PREEMPTION_DELAY_SECONDS

            info["emergency_preemption_active"] = 1

            self.event_logger.log(
                time_step=time_step,
                event_type="emergency_preemption",
                message=(
                    f"Emergency signal preemption activated at intersection "
                    f"{source}. Priority direction: {direction}."
                ),
                severity="warning",
                dedupe_key=f"emergency_preemption_{time_step}_{source}",
            )

        else:
            queue_delay = (
                    sum(self.queues[source].values())
                    * EMERGENCY_NO_PRIORITY_QUEUE_DELAY_WEIGHT
            )

            self.emergency_delay_seconds += (
                    EMERGENCY_NO_PRIORITY_BASE_DELAY_SECONDS
                    + queue_delay
            )

            self.event_logger.log(
                time_step=time_step,
                event_type="emergency_no_priority",
                message=(
                    f"Emergency vehicle delayed at intersection {source}; "
                    "priority mode disabled."
                ),
                severity="warning",
                dedupe_key=f"emergency_no_priority_{time_step}_{source}",
            )

        return info

def run_simulation_with_controller(
    num_intersections: int,
    demand_df: pd.DataFrame,
    controller: BaseTrafficController,
    scenario: str = "normal",
    enable_emergency_priority: bool = True,
) -> Dict[str, object]:
    """
    Convenience function to run any controller.
    """
    simulator = QueueTrafficSimulator(
        num_intersections=num_intersections,
        demand_df=demand_df,
        scenario=scenario,
        enable_emergency_priority=enable_emergency_priority,
    )

    return simulator.run(controller=controller)


def run_fixed_equal_simulation(
    num_intersections: int,
    demand_df: pd.DataFrame,
    scenario: str = "normal",
    enable_emergency_priority: bool = True,
) -> Dict[str, object]:
    controller = FixedEqualController()
    return run_simulation_with_controller(
        num_intersections=num_intersections,
        demand_df=demand_df,
        controller=controller,
        scenario=scenario,
        enable_emergency_priority=enable_emergency_priority,
    )


def run_fixed_calibrated_simulation(
    num_intersections: int,
    demand_df: pd.DataFrame,
    scenario: str = "normal",
    enable_emergency_priority: bool = True,
) -> Dict[str, object]:
    """
    Run fixed calibrated timing baseline.

    For now, we calibrate using the same demand data for simplicity.
    In a production version, calibration should use historical training data.
    """
    controller = FixedCalibratedController(
        calibration_demand=demand_df,
    )

    return run_simulation_with_controller(
        num_intersections=num_intersections,
        demand_df=demand_df,
        controller=controller,
        scenario=scenario,
        enable_emergency_priority=enable_emergency_priority,
    )

def run_adaptive_simulation(
    num_intersections: int,
    demand_df: pd.DataFrame,
    queue_weight: float = 1.0,
    prediction_weight: float = 1.0,
    pedestrian_weight: float = 0.15,
    scenario: str = "normal",
    enable_emergency_priority: bool = True,
) -> Dict[str, object]:
    """
    Run adaptive pressure-based controller.
    """
    controller = AdaptivePressureController(
        queue_weight=queue_weight,
        prediction_weight=prediction_weight,
        pedestrian_weight=pedestrian_weight,
    )

    return run_simulation_with_controller(
        num_intersections=num_intersections,
        demand_df=demand_df,
        controller=controller,
        scenario=scenario,
        enable_emergency_priority=enable_emergency_priority,
    )

def run_enhanced_adaptive_simulation(
    num_intersections: int,
    demand_df: pd.DataFrame,
    queue_weight: float = 1.0,
    prediction_weight: float = 2.0,
    pedestrian_weight: float = 0.1,
    pressure_exponent: float = 2.0,
    adaptive_min_green: float = 5.0,
    scenario: str = "normal",
    enable_emergency_priority: bool = True,
) -> Dict[str, object]:
    """
    Run enhanced adaptive pressure-based controller.
    """
    controller = EnhancedAdaptiveController(
        queue_weight=queue_weight,
        prediction_weight=prediction_weight,
        pedestrian_weight=pedestrian_weight,
        pressure_exponent=pressure_exponent,
        adaptive_min_green=adaptive_min_green,
    )

    return run_simulation_with_controller(
        num_intersections=num_intersections,
        demand_df=demand_df,
        controller=controller,
        scenario=scenario,
        enable_emergency_priority=enable_emergency_priority,
    )

def run_ga_timing_plan_simulation(
    num_intersections: int,
    demand_df: pd.DataFrame,
    timing_plan: Dict[str, Dict[int, Dict[str, float]]],
    scenario: str = "normal",
    enable_emergency_priority: bool = True,
) -> Dict[str, object]:
    """
    Run GA-optimized timing plan.
    """
    controller = GATimingPlanController(
        timing_plan=timing_plan,
    )

    return run_simulation_with_controller(
        num_intersections=num_intersections,
        demand_df=demand_df,
        controller=controller,
        scenario=scenario,
        enable_emergency_priority=enable_emergency_priority,
    )